import { createApp } from 'vue';
import { Quasar } from 'quasar';
import router from './router/Index.js';
import { createPinia } from 'pinia';
import App from './App.vue';
import 'quasar/src/css/index.sass';
const app = createApp(App);
app.use(Quasar);
app.use(router);
app.use(createPinia());
app.mount('#app');
